### ISSUE TITLE
Error: Parse error: Unexpected ""

### ISSUE THREAD

**Issue by nbouvrette** [un-ts/prettier#242]
I am trying to Prettify `.sql` files and some of them contain functions such as this one:

```sql
CREATE FUNCTION test(character varying) RETURNS boolean
    LANGUAGE sql
    AS $_$
select exists (select 1 from "test2" where value = $1 and type = 'testType');
$_$;
```

Unfortunately, this seems to crash the plugin with the following stack trace:

```sh
["ERROR" - 2:35:00 p.m.] Error formatting document.
["ERROR" - 2:35:00 p.m.] Parse error: Unexpected "$_$
select exists (s"
Error: Parse error: Unexpected "$_$
select exists (s"
    at TokenizerEngine.tokenize (/test-app/node_modules/sql-formatter/src/lexer/TokenizerEngine.ts:48:17)
    at Tokenizer.tokenize (/test-app/node_modules/sql-formatter/src/lexer/Tokenizer.ts:26:47)
    at LexerAdapter.tokenize (/test-app/node_modules/sql-formatter/src/parser/createParser.ts:21:37)
    at LexerAdapter.reset (/test-app/node_modules/sql-formatter/src/parser/LexerAdapter.ts:15:24)
    at Parser.feed (/test-app/node_modules/nearley/lib/nearley.js:281:15)
    at Object.parse (/test-app/node_modules/sql-formatter/src/parser/createParser.ts:31:34)
    at SqlFormatter.parse (/test-app/node_modules/sql-formatter/src/formatter/Formatter.ts:57:49)
    at SqlFormatter.format (/test-app/node_modules/sql-formatter/src/formatter/Formatter.ts:49:22)
    at Object.format (/test-app/node_modules/sql-formatter/src/sqlFormatter.ts:76:36)
    at Object.print (/test-app/node_modules/prettier-plugin-sql/lib/index.cjs:183:66)
    at callPluginPrintFunction (/test-app/node_modules/prettier/index.js:8420:26)
    at mainPrintInternal (/test-app/node_modules/prettier/index.js:8369:22)
    at mainPrint (/test-app/node_modules/prettier/index.js:8356:18)
    at printAstToDoc (/test-app/node_modules/prettier/index.js:8348:18)
    at coreFormat (/test-app/node_modules/prettier/index.js:8653:20)
    at formatWithCursor2 (/test-app/node_modules/prettier/index.js:8837:18)
    at /test-app/node_modules/prettier/index.js:37229:12
    at Object.format (/test-app/node_modules/prettier/index.js:37243:12)
    at t.default.format (/test-app/.vscode/extensions/esbenp.prettier-vscode-9.9.0/dist/extension.js:1:14565)
    at t.PrettierEditProvider.provideEdits (/test-app/.vscode/extensions/esbenp.prettier-vscode-9.9.0/dist/extension.js:1:11259)
    at B.provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:45902)
["INFO" - 2:35:00 p.m.] Formatting completed in 8ms.
```

**Comment by JounQin** [comment]
It seems thrown from `sql-formatter`.

**Comment by JounQin** [comment]
Maybe you should post it to github.com/sql-formatter-org/sql-formatter instead

**Comment by nbouvrette** [comment]
Just [did](https://github.com/sql-formatter-org/sql-formatter/issues/589) @JounQin but I am not really familiar with this other repo if they need help reproducing the issue.

**Comment by nbouvrette** [comment]
@JounQin actually it looks like this is a non-issue. I was able to fix this by simply setting this config in my `.prettierrc.yaml`:

```yaml
  # Set all sql files to PostgreSQL
  - files: '*.sql'
    options:
      language: 'postgresql'
```

**Comment by klondikemarlen** [comment]
@nbouvrette Would you mind sharing more of your config? Where does the snippet go in relation to
```yaml
plugins:
  - prettier-plugin-sql
```

**Comment by nbouvrette** [comment]
@klondikemarlen sorry I should have clarified I'm using a `yaml` config file. If you are using a JSON file you can simply use this in your `.prettierrc.json` [config file](https://prettier.io/docs/en/configuration.html):

```json
{
  "plugins": [
    "prettier-plugin-sql"
  ]
}
```

**Comment by tawfiknasser** [comment]
Here is json format:
```
{
    "tabWidth": 2,
    "useTabs": false,
    "plugins": ["prettier-plugin-sql"],
    "overrides" :[
    {
      "files": ["*.sql"],
      "options":{
        "endOfLine": "lf",
        "language": "postgresql",
        "keywordCase": "upper"
      }
    }
  ]
}
```
