### ISSUE TITLE
[prettier-plugin-sh] Fails on if statement that checks command exists

### ISSUE THREAD

**Issue by agreedSkiing** [un-ts/prettier#253]
When formatting a file that checks if a command exists with command -v the formatting fails.

### Reproducer

```bash
#!/bin/sh

echo "Starting setup of this project"

if [[ ! command -v npm > /dev/null 2>&1 ]] ; then
    echo "Missing npm, stopping script"
    exit
fi
```

#### Terminal (oh-my-zsh with power10k)

```zsh
$ npx prettier --write setup.sh
setup.sh
[error] setup.sh: SyntaxError: not a valid test operator: npm
[error]    5 | echo "Starting setup of this project"
[error]    6 |
[error] >  7 | if [[ ! command npm > /dev/null 2>&1 ]] ; then
[error]      |                 ^
[error]    8 |     echo "Missing npm, stopping script"
[error]    9 |     exit
[error]   10 | fi
```

#### VSCode

Plugin:
```text
Name: Prettier - Code formatter
Id: esbenp.prettier-vscode
Description: Code formatter using prettier
Version: 9.10.4
Publisher: Prettier
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode
```

VSCode version
```text
Version: 1.74.3 (user setup)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No
```

Log from plugin

```log
["INFO" - 3:25:30 PM] Formatting file:///home/eriase/repos/all-prettier-java-project/setup.sh
["INFO" - 3:25:30 PM] Using config file at '/home/eriase/repos/all-prettier-java-project/.prettierrc'
["INFO" - 3:25:30 PM] Using ignore file (if present) at /home/eriase/repos/all-prettier-java-project/.prettierignore
["INFO" - 3:25:30 PM] File Info:
{
  "ignored": false,
  "inferredParser": "sh"
}
["INFO" - 3:25:30 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 3:25:30 PM] Prettier Options:
{
  "filepath": "/home/eriase/repos/all-prettier-java-project/setup.sh",
  "parser": "sh",
  "tabWidth": 4,
  "useTabs": false,
  "endOfLine": "lf",
  "printWidth": 120,
  "trailingComma": "none",
  "semi": true,
  "xmlWhitespaceSensitivity": "ignore",
  "htmlWhitespaceSensitivity": "ignore",
  "bracketSameLine": false,
  "singleAttributePerLine": true
}
["ERROR" - 3:25:30 PM] Error formatting document.
["ERROR" - 3:25:30 PM] not a valid test operator: -v
  3 | echo "Starting setup of this project"
  4 |
> 5 | if [[ ! command -v npm > /dev/null 2>&1 ]] ; then
    |                 ^
  6 |     echo "Missing npm, stopping script"
  7 |     exit
  8 | fi
SyntaxError: not a valid test operator: -v
  3 | echo "Starting setup of this project"
  4 |
> 5 | if [[ ! command -v npm > /dev/null 2>&1 ]] ; then
    |                 ^
  6 |     echo "Missing npm, stopping script"
  7 |     exit
  8 | fi
	at Object.parse (/home/eriase/repos/all-prettier-java-project/node_modules/prettier-plugin-sh/lib/index.cjs:442:17)
	at Object.parse (/home/eriase/repos/all-prettier-java-project/node_modules/prettier/index.js:7515:23)
	at coreFormat (/home/eriase/repos/all-prettier-java-project/node_modules/prettier/index.js:8829:18)
	at formatWithCursor2 (/home/eriase/repos/all-prettier-java-project/node_modules/prettier/index.js:9021:18)
	at /home/eriase/repos/all-prettier-java-project/node_modules/prettier/index.js:38168:12
	at Object.format (/home/eriase/repos/all-prettier-java-project/node_modules/prettier/index.js:38182:12)
	at t.default.format (/home/eriase/.vscode-server/extensions/esbenp.prettier-vscode-9.10.4/dist/extension.js:1:14669)
	at async t.PrettierEditProvider.provideEdits (/home/eriase/.vscode-server/extensions/esbenp.prettier-vscode-9.10.4/dist/extension.js:1:11355)
	at async B.provideDocumentFormattingEdits (/home/eriase/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/out/vs/workbench/api/node/extensionHostProcess.js:96:39719)
["INFO" - 3:25:30 PM] Formatting completed in 9ms.
```

### Config

Package.json

```json
{
    "lint-staged": {
        "*.{html,sql,xml,sh,yaml,json,md,java}": "prettier --write"
    },
    "devDependencies": {
        "@prettier/plugin-xml": "^2.2.0",
        "husky": "^8.0.3",
        "lint-staged": "^13.1.0",
        "prettier": "^2.8.3",
        "prettier-plugin-java": "^2.0.0",
        "prettier-plugin-properties": "^0.2.0",
        "prettier-plugin-sh": "^0.12.8",
        "prettier-plugin-sql": "^0.12.1",
        "pretty-quick": "^3.1.3"
    }
}
```

.prettierrc
```json
{
    "tabWidth": 4,
    "useTabs": false,
    "endOfLine": "lf",
    "printWidth": 120,
    "trailingComma": "none",
    "semi": true,
    "xmlWhitespaceSensitivity": "ignore",
    "htmlWhitespaceSensitivity": "ignore",
    "bracketSameLine": false,
    "singleAttributePerLine": true
}
```

**Comment by agreedSkiing** [comment]
Sorry the script didn't event work with that if statement
