### ISSUE TITLE
[prettier-plugin-toml] unable to format `toml` programmatically in an es module

### ISSUE THREAD

**Issue by Sec-ant** [un-ts/prettier#317]
Following setup:

- `package.json`
  ```json
  {
    "name": "prettier-plugin-toml-test",
    "version": "1.0.0",
    "description": "",
    "type": "module",
    "main": "index.js",
    "scripts": {
      "test": "echo \"Error: no test specified\" && exit 1"
    },
    "keywords": [],
    "author": "",
    "license": "ISC",
    "devDependencies": {
      "prettier": "^3.1.0",
      "prettier-plugin-toml": "^2.0.0"
    }
  }
  ```

- `index.js`
  ```js
  import { format } from "prettier";
  
  const code = `[foo]
  asfd  =            1
  bar=['averyloooooooooooooooooooooooooooooooooooooooooooooooooooong', "arrrrrrrrrrrrrrrrrrrrrrrray",'thatexceedsthemaximumcolumnwidth']`;
  
  format(code, {
    plugins: ["prettier-plugin-toml"],
    filepath: "a.toml",
  }).then(console.log);
  ```

- `shell command`
  ```shell
  node ./index.js
  ```

- `output`
  ```shell
  file:///home/secant/prettier-plugin-toml-test/node_modules/prettier-plugin-toml/lib/index.js:1
  import { Taplo } from '@taplo/lib';
           ^^^^^
  SyntaxError: Named export 'Taplo' not found. The requested module '@taplo/lib' is a CommonJS module, which may not support all module.exports as named exports.
  CommonJS modules can always be imported via the default export, for example using:
  
  import pkg from '@taplo/lib';
  const { Taplo } = pkg;
  
      at ModuleJob._instantiate (node:internal/modules/esm/module_job:131:21)
      at async ModuleJob.run (node:internal/modules/esm/module_job:213:5)
      at async ModuleLoader.import (node:internal/modules/esm/loader:308:24)
      at async loadPlugin (file:///home/secant/prettier-plugin-toml-test/node_modules/prettier/index.mjs:22690:28)
      at async Promise.all (index 0)
      at async Promise.all (index 1)
      at async file:///home/secant/prettier-plugin-toml-test/node_modules/prettier/index.mjs:23988:17
      at async format2 (file:///home/secant/prettier-plugin-toml-test/node_modules/prettier/index.mjs:23999:25)
  
  Node.js v20.6.1
  ```

**Comment by JounQin** [comment]
Thanks for reporting, I'll fix this quickly.

**Comment by Sec-ant** [comment]
A bit of a tangent: can you also export the type `PrettierTaploOptions` so I can add this plugin in `prettier-plugin-embed` with the proper types?

**Comment by JounQin** [comment]
> A bit of a tangent: can you also export the type `PrettierTaploOptions` so I can add this plugin in `prettier-plugin-embed` with the proper type for the options?

Sure~

**Comment by JounQin** [comment]
@Sec-ant Is you request here the same thing as #311?

**Comment by Sec-ant** [comment]
> @Sec-ant Is you request here the same thing as #311?

Sort of. I'd love a union type of `SqlBaseOptions["languages"]` or `SqlBaseOptions["database"]`. But they're `string` right now.
