### ISSUE TITLE
prettier-plugin-sql handling of sql-formatter errors

### ISSUE THREAD

**Issue by tylersayshi** [un-ts/prettier#395]
Is it possible to either by default or by configuration have the plugin throw a prettier error when invalid sql is found?

Maybe there is a better way to handle this, but currently the error is thrown in the prettier process, but prettier's checks still pass.

partial error:

```
A RESERVED_PHRASE token based on:
    keyword$subexpression$1 →  ● %RESERVED_PHRASE
    keyword →  ● keyword$subexpression$1
    atomic_expression$subexpression$1 →  ● keyword
    atomic_expression →  ● atomic_expression$subexpression$1
    asteriskless_andless_expression$subexpression$1 →  ● atomic_expression
    asteriskless_andless_expression →  ● asteriskless_andless_expression$subexpression$1
    asteriskless_free_form_sql$subexpression$1 →  ● asteriskless_andless_expression
    asteriskless_free_form_sql →  ● asteriskless_free_form_sql$subexpression$1
    free_form_sql$subexpression$1 →  ● asteriskless_free_form_sql
    free_form_sql →  ● free_form_sql$subexpression$1
    expressions_or_clauses$ebnf$1 → expressions_or_clauses$ebnf$1 ● free_form_sql
    expressions_or_clauses →  ● expressions_or_clauses$ebnf$1 expressions_or_clauses$ebnf$2
    statement →  ● expressions_or_clauses statement$subexpression$1
    main$ebnf$1 → main$ebnf$1 ● statement
    main →  ● main$ebnf$1
A RESERVED_JOIN token based on:
    keyword$subexpression$1 →  ● %RESERVED_JOIN
    keyword →  ● keyword$subexpression$1
    atomic_expression$subexpression$1 →  ● keyword
    atomic_expression →  ● atomic_expression$subexpression$1
    asteriskless_andless_expression$subexpression$1 →  ● atomic_expression
    asteriskless_andless_expression →  ● asteriskless_andless_expression$subexpression$1
    asteriskless_free_form_sql$subexpression$1 →  ● asteriskless_andless_expression
    asteriskless_free_form_sql →  ● asteriskless_free_form_sql$subexpression$1
    free_form_sql$subexpression$1 →  ● asteriskless_free_form_sql
    free_form_sql →  ● free_form_sql$subexpression$1
    expressions_or_clauses$ebnf$1 → expressions_or_clauses$ebnf$1 ● free_form_sql
    expressions_or_clauses →  ● expressions_or_clauses$ebnf$1 expressions_or_clauses$ebnf$2
    statement →  ● expressions_or_clauses statement$subexpression$1
    main$ebnf$1 → main$ebnf$1 ● statement
    main →  ● main$ebnf$1

    at Parser.feed (~/gitspace/falcon/node_modules/nearley/lib/nearley.js:343:27)
    at Object.parse (file:///~/gitspace/falcon/node_modules/sql-formatter/dist/index.js:16813:34)
    at Formatter.parse (file:///~/gitspace/falcon/node_modules/sql-formatter/dist/index.js:17522:49)
    at Formatter.format (file:///~/gitspace/falcon/node_modules/sql-formatter/dist/index.js:17517:22)
    at formatDialect (file:///~/gitspace/falcon/node_modules/sql-formatter/dist/index.js:17640:57)
    at format (file:///~/gitspace/falcon/node_modules/sql-formatter/dist/index.js:17630:10)
    at Object.print (file:///~/gitspace/falcon/node_modules/prettier-plugin-sql/lib/index.js:41:31)
    at callPluginPrintFunction (file:///~/gitspace/falcon/node_modules/prettier/index.mjs:20871:20)
    at printAstToDoc (file:///~/gitspace/falcon/node_modules/prettier/index.mjs:20826:22)
    at async textToDoc (file:///~/gitspace/falcon/node_modules/prettier/index.mjs:20793:16) {
  offset: 8,
  token: {
    type: 'CLOSE_PAREN',
    raw: ')',
    text: ')',
    start: 40,
    precedingWhitespace: '\n'
  }
}
All matched files use Prettier code style!
```

**Comment by JounQin** [comment]
Not quite sure to understand, please provide a runnable reproduction?

**Comment by tylersayshi** [comment]
I'm realizing that I was confused with the responsibility of things here. I filed the issue hoping for a prettier formatting error to be thrown when the sql being formatted is invalid.

In the case I added above, there was a missing paren and prettier passed still with `All matched files use Prettier code style!`. This is expected and correct.

If I want to check for valid sql I should add a linter or something. This is just not the responsibility of the formatter.

Apologies for the distraction here and thanks for the great plugin!
